import { Inject, Injectable } from '@nestjs/common';
import { PrismaService } from '@/common/prisma/prisma.service';
import { BusinessException } from '@/common/exceptions/business.exception';
import { encrypt, decrypt } from '@/common/utils/crypto.util';
import {
  PaginatedDto,
  buildMeta,
  parsePagination,
  skipTake,
} from '@/common/pagination/pagination.dto';
import {
  PANEL_CLIENTS,
  type IPanelClient,
  type PanelConnection,
  type PanelHealth,
} from './panel-client.interface';

export interface PanelDto {
  id: string;
  publicId: string;
  name: string;
  type: string;
  baseUrl: string;
  isActive: boolean;
  isHealthy: boolean | null;
  lastHealthCheckAt: Date | null;
  extraConfig: Record<string, unknown> | null;
  createdAt: Date;
}

/**
 * PanelsService - admin management of VpnPanel instances + panel client
 * resolution. The apiKey is encrypted at rest and only decrypted when building
 * a PanelConnection for a transient API call.
 */
@Injectable()
export class PanelsService {
  constructor(
    private readonly prisma: PrismaService,
    @Inject(PANEL_CLIENTS) private readonly clients: Map<string, IPanelClient>,
  ) {}

  /** Get the IPanelClient for a given panel type. */
  getClient(type: string): IPanelClient {
    const client = this.clients.get(type);
    if (!client) throw BusinessException.conflict(`No panel client for type '${type}'`);
    return client;
  }

  /** Build a transient PanelConnection (decrypted) for API calls. */
  async getConnection(panelId: bigint): Promise<PanelConnection> {
    const panel = await this.prisma.vpnPanel.findUnique({ where: { id: panelId } });
    if (!panel) throw BusinessException.notFound('Panel not found');
    if (panel.status !== 'ACTIVE') throw BusinessException.conflict('Panel is inactive');
    return {
      id: panel.id,
      name: panel.name,
      type: panel.type,
      baseUrl: panel.baseUrl,
      apiKey: decrypt(panel.apiKey),
      extraConfig: (panel.metadata as Record<string, unknown>) ?? undefined,
    };
  }

  async list(query: Record<string, unknown>): Promise<PaginatedDto<PanelDto>> {
    const params = parsePagination(query);
    const where: Record<string, unknown> = {};
    if (query.type) where.type = query.type;
    if (query.isActive !== undefined) where.status = query.isActive === 'true' ? 'ACTIVE' : 'INACTIVE';
    const [total, items] = await Promise.all([
      this.prisma.vpnPanel.count({ where }),
      this.prisma.vpnPanel.findMany({ where, ...skipTake(params), orderBy: { createdAt: 'desc' } }),
    ]);
    return { data: items.map((p) => this.toDto(p)), meta: buildMeta(total, params) };
  }

  async create(input: {
    name: string;
    type: string;
    baseUrl: string;
    apiKey: string;
    isActive?: boolean;
    extraConfig?: Record<string, unknown>;
  }): Promise<PanelDto> {
    const panel = await this.prisma.vpnPanel.create({
      data: {
        // publicId is auto-generated by the schema (@default(uuid())).
        name: input.name,
        type: input.type as any,
        baseUrl: input.baseUrl,
        apiKey: encrypt(input.apiKey),
        status: input.isActive === false ? 'INACTIVE' : 'ACTIVE',
        metadata: (input.extraConfig ?? {}) as any,
      },
    });
    return this.toDto(panel);
  }

  async update(id: bigint, input: Record<string, unknown>): Promise<PanelDto> {
    const data: Record<string, unknown> = {};
    if (input.name !== undefined) data.name = input.name;
    if (input.type !== undefined) data.type = input.type;
    if (input.baseUrl !== undefined) data.baseUrl = input.baseUrl;
    if (input.isActive !== undefined) data.status = input.isActive ? 'ACTIVE' : 'INACTIVE';
    if (input.extraConfig !== undefined) data.metadata = input.extraConfig;
    if (input.apiKey !== undefined) {
      data.apiKey = encrypt(input.apiKey as string);
    }
    const panel = await this.prisma.vpnPanel.update({ where: { id }, data });
    return this.toDto(panel);
  }

  async delete(id: bigint): Promise<void> {
    const servers = await this.prisma.server.count({ where: { panelId: id } });
    if (servers > 0) throw BusinessException.conflict('Panel is in use by servers; reassign them first');
    await this.prisma.vpnPanel.delete({ where: { id } });
  }

  /** Probe panel health and persist the result. */
  async checkHealth(id: bigint): Promise<PanelHealth> {
    const connection = await this.getConnection(id);
    const client = this.getClient(connection.type ?? 'SANITY');
    const health = await client.health(connection);
    await this.prisma.vpnPanel.update({
      where: { id },
      data: {
        healthStatus: health.reachable ? 'HEALTHY' : 'UNHEALTHY',
        lastSyncAt: new Date(),
        metadata: {
          version: health.version,
          activeUsers: health.activeUsers,
          totalUsers: health.totalUsers,
          cpuUsage: health.cpuUsage,
          memoryUsage: health.memoryUsage,
          latencyMs: health.latencyMs,
        },
      },
    });
    return health;
  }

  private toDto(p: any): PanelDto {
    return {
      id: p.id.toString(),
      publicId: p.publicId,
      name: p.name,
      type: p.type,
      baseUrl: p.baseUrl,
      isActive: p.status === 'ACTIVE',
      isHealthy: p.healthStatus === 'HEALTHY' ? true : p.healthStatus === 'UNHEALTHY' ? false : null,
      lastHealthCheckAt: p.lastSyncAt,
      extraConfig: (p.metadata as Record<string, unknown>) ?? null,
      createdAt: p.createdAt,
    };
  }
}
