import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '@/common/prisma/prisma.service';
import { BusinessException } from '@/common/exceptions/business.exception';
import {
  PaginatedDto,
  buildMeta,
  parsePagination,
  skipTake,
} from '@/common/pagination/pagination.dto';
import { randomUUID } from 'node:crypto';

export interface TicketDto {
  id: string;
  publicId: string;
  subject: string;
  category: string;
  priority: string;
  status: string;
  userId: string;
  assigneeId: string | null;
  messageCount: number;
  lastReplyAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface TicketMessageDto {
  id: string;
  publicId: string;
  ticketId: string;
  senderId: string;
  senderRole: 'USER' | 'AGENT' | 'SYSTEM';
  body: string;
  attachmentFileKey: string | null;
  isRead: boolean;
  createdAt: Date;
}

/**
 * TicketsService - support ticket system with threaded messages.
 * Users create tickets; agents (admin/support) reply. Notifications are
 * enqueued so users get pinged on Telegram/in-app.
 */
@Injectable()
export class TicketsService {
  private readonly logger = new Logger(TicketsService.name);

  constructor(
    private readonly prisma: PrismaService,
  ) {}

  async create(input: {
    userId: bigint;
    subject: string;
    category: string;
    priority: string;
    message: string;
    attachmentFileKey?: string;
  }): Promise<TicketDto> {
    const ticket = await this.prisma.ticket.create({
      data: {
        // publicId is auto-generated by the schema (@default(uuid())).
        subject: input.subject,
        category: input.category,
        priority: input.priority as any,
        status: 'OPEN',
        userId: input.userId,
        messages: {
          create: {
            // TicketMessage uses `userId` (not senderId), `senderType`
            // (not senderRole), `readAt` (not isRead). There is no metadata
            // field; attachments are a separate TicketAttachment model.
            userId: input.userId,
            senderType: 'USER',
            body: input.message,
          },
        },
      },
      include: { _count: { select: { messages: true } } },
    });
    await this.notifyAgents(ticket.id, input.subject);
    return this.toDto(ticket);
  }

  async reply(input: {
    ticketPublicId: string;
    senderId: bigint;
    senderRole: 'USER' | 'AGENT';
    message: string;
    attachmentFileKey?: string;
  }): Promise<TicketMessageDto> {
    const ticket = await this.getTicket(input.ticketPublicId, input.senderId, input.senderRole);
    if (ticket.status === 'CLOSED') throw BusinessException.conflict('Ticket is closed');

    const message = await this.prisma.ticketMessage.create({
      data: {
        // TicketMessage has no metadata field; attachments use a separate model.
        ticketId: ticket.id,
        userId: input.senderId,
        senderType: input.senderRole,
        body: input.message,
      },
    });

    // Update ticket status. TicketStatus has no PENDING — use PENDING_AGENT
    // (user replied, awaiting agent) / PENDING_USER (agent replied, awaiting
    // user). updatedAt is @updatedAt (auto). No lastReplyAt field exists.
    await this.prisma.ticket.update({
      where: { id: ticket.id },
      data: {
        status: input.senderRole === 'USER' ? 'PENDING_AGENT' : 'PENDING_USER',
      },
    });

    // Notify the other party. NotificationChannel has no IN_APP — use PUSH.
    // Notification: ticket reply was sent (logging only for now).
    const notifyUserId = input.senderRole === 'USER' ? null : ticket.userId;
    if (notifyUserId) {
      this.logger.log(`Ticket reply notification: user ${notifyUserId}, ticket ${ticket.subject}`);
    }

    return this.toMessageDto(message);
  }

  async getMessages(
    ticketPublicId: string,
    userId: bigint,
    role: 'USER' | 'AGENT',
  ): Promise<TicketMessageDto[]> {
    const ticket = await this.getTicket(ticketPublicId, userId, role);
    const messages = await this.prisma.ticketMessage.findMany({
      where: { ticketId: ticket.id },
      orderBy: { createdAt: 'asc' },
    });

    // Mark user messages as read when agent views.
    // TicketMessage uses `senderType` (not senderRole) and `readAt` (not isRead).
    if (role === 'AGENT') {
      await this.prisma.ticketMessage.updateMany({
        where: { ticketId: ticket.id, senderType: 'USER', readAt: null },
        data: { readAt: new Date() },
      });
    }
    return messages.map((m) => this.toMessageDto(m));
  }

  async listMine(userId: bigint, query: Record<string, unknown>): Promise<PaginatedDto<TicketDto>> {
    const params = parsePagination(query);
    const where: Record<string, unknown> = { userId };
    if (query.status) where.status = query.status;
    const [total, items] = await Promise.all([
      this.prisma.ticket.count({ where }),
      this.prisma.ticket.findMany({
        where,
        ...skipTake(params),
        orderBy: { updatedAt: 'desc' },
        include: { _count: { select: { messages: true } } },
      }),
    ]);
    return { data: items.map((t) => this.toDto(t)), meta: buildMeta(total, params) };
  }

  async listAll(query: Record<string, unknown>): Promise<PaginatedDto<TicketDto>> {
    const params = parsePagination(query);
    const where: Record<string, unknown> = {};
    if (query.status) where.status = query.status;
    if (query.category) where.category = query.category;
    if (query.priority) where.priority = query.priority;
    if (query.assigneeId) where.assigneeId = BigInt(query.assigneeId as string);
    const [total, items] = await Promise.all([
      this.prisma.ticket.count({ where }),
      this.prisma.ticket.findMany({
        where,
        ...skipTake(params),
        orderBy: { updatedAt: 'desc' },
        include: { _count: { select: { messages: true } } },
      }),
    ]);
    return { data: items.map((t) => this.toDto(t)), meta: buildMeta(total, params) };
  }

  async updateStatus(
    ticketPublicId: string,
    input: { status: string; assigneeId?: bigint },
  ): Promise<TicketDto> {
    const ticket = await this.prisma.ticket.findUnique({ where: { publicId: ticketPublicId } });
    if (!ticket) throw BusinessException.notFound('Ticket not found');
    const updated = await this.prisma.ticket.update({
      where: { id: ticket.id },
      data: {
        status: input.status as any,
        ...(input.assigneeId ? { assigneeId: input.assigneeId } : {}),
      },
      include: { _count: { select: { messages: true } } },
    });
    return this.toDto(updated);
  }

  private async getTicket(publicId: string, userId: bigint, role: 'USER' | 'AGENT') {
    const ticket = await this.prisma.ticket.findUnique({ where: { publicId } });
    if (!ticket) throw BusinessException.notFound('Ticket not found');
    if (role === 'USER' && ticket.userId !== userId) {
      throw BusinessException.forbidden('Not your ticket');
    }
    return ticket;
  }

  private async notifyAgents(ticketId: bigint, subject: string): Promise<void> {
    this.logger.log(`New support ticket #${ticketId}: ${subject}`);
  }

  private toDto(t: any): TicketDto {
    return {
      id: t.id.toString(),
      publicId: t.publicId,
      subject: t.subject,
      category: t.category,
      priority: t.priority,
      status: t.status,
      userId: t.userId.toString(),
      assigneeId: t.assigneeId?.toString() ?? null,
      messageCount: t._count?.messages ?? 0,
      // No lastReplyAt field; fall back to updatedAt.
      lastReplyAt: t.updatedAt ?? null,
      createdAt: t.createdAt,
      updatedAt: t.updatedAt,
    };
  }

  private toMessageDto(m: any): TicketMessageDto {
    return {
      id: m.id.toString(),
      publicId: m.id.toString(),
      ticketId: m.ticketId.toString(),
      // TicketMessage uses `userId` (not senderId) and `senderType` (not
      // senderRole). Attachments live in metadata; read state is `readAt`.
      senderId: m.userId.toString(),
      senderRole: m.senderType,
      body: m.body,
      attachmentFileKey: m.metadata?.attachmentFileKey ?? null,
      isRead: !!m.readAt,
      createdAt: m.createdAt,
    };
  }
}
