#!/usr/bin/env bash
# Read-only probe of the target host before installing anything.
echo "host=$(hostname) arch=$(uname -m) user=$(whoami)"
echo "os=$(. /etc/os-release 2>/dev/null; echo "$PRETTY_NAME")"
echo "node=$(node -v 2>/dev/null || echo MISSING)"
echo "npm=$(npm -v 2>/dev/null || echo MISSING)"
echo "git=$(git --version 2>/dev/null || echo MISSING)"
echo "docker=$(docker --version 2>/dev/null || echo MISSING)"
echo "compose=$(docker compose version --short 2>/dev/null || echo MISSING)"
echo "--- existing tazaxy ---"
echo "launcher=$(command -v tazaxy || echo NONE)"
echo "workspace=$([ -d /opt/tazaxy ] && echo PRESENT || echo NONE)"
echo "--- 3x-ui (must be preserved) ---"
echo "xui_service=$(systemctl is-active x-ui 2>/dev/null || echo inactive)"
echo "xui_db=$(sha256sum /etc/x-ui/x-ui.db 2>/dev/null | cut -c1-16 || echo MISSING)"
ss -ltnp 2>/dev/null | grep -E ':(17342|2096)\b' || echo "panel ports not bound"
echo "--- outbound reachability ---"
echo "github=$(curl -sS -o /dev/null -m 15 -w '%{http_code}' https://github.com 2>&1 || echo UNREACHABLE)"
echo "telegram=$(curl -sS -o /dev/null -m 15 -w '%{http_code}' https://api.telegram.org 2>&1 || echo UNREACHABLE)"
echo "registry=$(curl -sS -o /dev/null -m 15 -w '%{http_code}' https://registry.npmjs.org 2>&1 || echo UNREACHABLE)"
