#!/usr/bin/env node
/**
 * auto-config.js
 *
 * Smart auto-configuration engine for the VPN SaaS installer.
 * Performs discovery-first configuration: detects everything it can from
 * the environment, Docker, existing config files, and installer-state cache
 * BEFORE asking the user any questions. Only genuinely undiscoverable values
 * (e.g. Telegram bot token) prompt the user.
 *
 * Design principles:
 *  - Never ask before discovery is complete.
 *  - Cache results in installer-state.json with timestamps + validation.
 *  - Generate secrets (JWT, S3 keys, encryption key) automatically.
 *  - Recover existing credentials from .env, docker-compose, shared env.
 *  - One canonical .env written by the installer, read by everyone.
 *
 * Exports:
 *  - runAutoConfig(opts) → Promise<{ config, changed, prompts }>
 */
'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { exec } = require('child_process');
const { loadState, saveState, setEntry, getValidatedEntry } = require('./state-manager');

const STATE_PATH = path.resolve(process.cwd(), 'installer-state.json');
const ENV_PATH = path.resolve(process.cwd(), '.env');
const ENV_EXAMPLE_PATH = path.resolve(process.cwd(), '.env.example');

// ── Helpers ────────────────────────────────────────────────────────

function runCmd(cmd, opts = {}) {
  const timeout = opts.timeout || 10000;
  return new Promise((resolve) => {
    exec(cmd, { timeout, shell: true }, (err, stdout, stderr) => {
      resolve({
        success: !err,
        code: err && err.code != null ? err.code : 0,
        stdout: stdout ? stdout.trim() : '',
        stderr: stderr ? stderr.trim() : '',
      });
    });
  });
}

function parseEnvFile(content) {
  const out = {};
  if (!content) return out;
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx < 0) continue;
    const key = trimmed.substring(0, eqIdx).trim();
    let value = trimmed.substring(eqIdx + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

function loadEnvFile(filePath) {
  try {
    if (fs.existsSync(filePath)) return parseEnvFile(fs.readFileSync(filePath, 'utf8'));
  } catch (_) { /* non-fatal */ }
  return {};
}

function writeEnvFile(filePath, envObj) {
  const lines = [];
  lines.push('# =============================================================================');
  lines.push('# VPN SaaS - Environment Configuration (Auto-generated by installer)');
  lines.push('# Do not edit manually while the installer is running.');
  lines.push('# =============================================================================');
  lines.push('');

  const sections = {
    'Application': ['NODE_ENV', 'APP_NAME', 'APP_PORT', 'APP_HOST', 'APP_URL', 'API_PREFIX', 'API_VERSION', 'GLOBAL_PREFIX', 'CORS_ORIGINS', 'RATE_LIMIT_TTL', 'RATE_LIMIT_LIMIT'],
    'Database (PostgreSQL)': ['DATABASE_URL', 'POSTGRES_HOST', 'POSTGRES_PORT', 'POSTGRES_USER', 'POSTGRES_PASSWORD', 'VPN_DATABASE', 'XUI_DATABASE', 'PRISMA_MIGRATE_ON_BOOT', 'DATABASE_SEED', 'DATABASE_POOL_MIN', 'DATABASE_POOL_MAX'],
    'Redis / Cache': ['REDIS_HOST', 'REDIS_PORT', 'REDIS_PASSWORD', 'REDIS_DB', 'CACHE_TTL_DEFAULT'],
    'JWT / Auth': ['JWT_ACCESS_SECRET', 'JWT_REFRESH_SECRET', 'JWT_ACCESS_TTL', 'JWT_REFRESH_TTL', 'JWT_ISSUER', 'JWT_AUDIENCE'],
    'S3 Compatible Storage': ['S3_ENDPOINT', 'S3_REGION', 'S3_BUCKET', 'S3_ACCESS_KEY', 'S3_SECRET_KEY', 'S3_FORCE_PATH_STYLE', 'S3_PUBLIC_URL'],
    'Telegram Bot': ['TELEGRAM_BOT_TOKEN', 'TELEGRAM_BOT_WEBHOOK_URL', 'TELEGRAM_BOT_WEBHOOK_PATH', 'TELEGRAM_BOT_USE_WEBHOOK', 'TELEGRAM_ADMIN_IDS', 'TELEGRAM_MINI_APP_URL'],
    'Sanity VPN Panel Integration': ['SANITY_PANEL_BASE_URL', 'SANITY_PANEL_API_KEY', 'SANITY_PANEL_USERNAME', 'SANITY_PANEL_PASSWORD', 'SANITY_PANEL_TIMEOUT_MS', 'SANITY_PANEL_MAX_RETRIES', 'SANITY_PANEL_SYNC_CRON', 'SANITY_PANEL_SUB_PORT', 'SANITY_PANEL_SUB_PATH'],
    '3X-UI Shared Database Integration': ['XUI_DB_TYPE', 'XUI_DB_DSN', 'XUI_PANEL_URL', 'XUI_USERNAME', 'XUI_PASSWORD'],
    'Payment Gateways': ['ONLINE_GATEWAY_ENABLED', 'ONLINE_GATEWAY_BASE_URL', 'ONLINE_GATEWAY_MERCHANT_ID', 'ONLINE_GATEWAY_API_KEY', 'ONLINE_GATEWAY_CALLBACK_URL', 'CRYPTO_ENABLED', 'CRYPTO_API_BASE_URL', 'CRYPTO_API_KEY', 'CRYPTO_WEBHOOK_SECRET', 'CARD_TO_CARD_ENABLED', 'CARD_TO_CARD_CARD_NUMBER', 'CARD_TO_CARD_HOLDER_NAME'],
    'Security': ['BCRYPT_ROUNDS', 'WEBHOOK_SECRET', 'ENCRYPTION_KEY', 'COOKIE_SECURE', 'CSRF_ENABLED'],
    'Storage Limits': ['MAX_UPLOAD_SIZE_MB', 'RECEIPT_ALLOWED_MIMES'],
    'Queue / BullMQ': ['QUEUE_PREFIX', 'QUEUE_DEFAULT_ATTEMPTS', 'QUEUE_DEFAULT_BACKOFF', 'QUEUE_DEFAULT_BACKOFF_DELAY'],
    'Monitoring': ['PINO_LEVEL', 'PINO_PRETTY', 'PROMETHEUS_ENABLED', 'PROMETHEUS_PATH', 'HEALTH_CHECK_PATH', 'BULL_BOARD_PATH'],
    'Super Admin (seed)': ['SUPER_ADMIN_EMAIL', 'SUPER_ADMIN_PASSWORD', 'SUPER_ADMIN_TELEGRAM_ID'],
  };

  for (const [sectionName, keys] of Object.entries(sections)) {
    lines.push(`# ---------- ${sectionName} ----------`);
    for (const key of keys) {
      const val = envObj[key] !== undefined ? envObj[key] : '';
      lines.push(`${key}=${val}`);
    }
    lines.push('');
  }

  fs.writeFileSync(filePath, lines.join('\n'), 'utf8');
}

function generateSecret(length = 48) {
  return crypto.randomBytes(length).toString('base64url').slice(0, length);
}

function generatePassword(length = 24) {
  return crypto.randomBytes(length).toString('base64url').slice(0, length);
}

function prompt(question, defaultValue) {
  // Synchronous prompt using readline
  const readline = require('readline');
  return new Promise((resolve) => {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    const promptText = defaultValue ? `${question} [${defaultValue}]: ` : `${question}: `;
    rl.question(promptText, (answer) => {
      rl.close();
      const trimmed = answer.trim();
      resolve(trimmed || defaultValue || '');
    });
  });
}

// ── Discovery functions ─────────────────────────────────────────────

/**
 * Discover PostgreSQL configuration from multiple sources.
 * Priority: existing .env DATABASE_URL > docker compose > shared env > local probe.
 */
async function discoverPostgreSQL(existingEnv) {
  const discovered = { host: null, port: null, user: null, password: null, database: null, databaseUrl: null, source: null };

  // 1. Existing .env DATABASE_URL
  if (existingEnv.DATABASE_URL) {
    try {
      const url = new URL(existingEnv.DATABASE_URL);
      discovered.host = url.hostname;
      discovered.port = url.port || '5432';
      discovered.user = url.username;
      discovered.password = url.password;
      discovered.database = url.pathname.slice(1).split('?')[0];
      discovered.databaseUrl = existingEnv.DATABASE_URL;
      discovered.source = 'env-database-url';
      return discovered;
    } catch (_) { /* invalid URL, continue */ }
  }

  // 2. Shared env files
  const sharedEnv = loadEnvFile('/opt/shared/.env');
  if (sharedEnv.DATABASE_URL) {
    try {
      const url = new URL(sharedEnv.DATABASE_URL);
      discovered.host = url.hostname;
      discovered.port = url.port || '5432';
      discovered.user = url.username;
      discovered.password = url.password;
      discovered.database = url.pathname.slice(1).split('?')[0];
      discovered.databaseUrl = sharedEnv.DATABASE_URL;
      discovered.source = 'shared-env';
      return discovered;
    } catch (_) { /* continue */ }
  }

  // 3. Postgres env file
  const pgEnv = loadEnvFile('/opt/postgres/.env');
  if (pgEnv.POSTGRES_HOST || pgEnv.POSTGRES_PORT || pgEnv.POSTGRES_USER || pgEnv.POSTGRES_PASSWORD) {
    discovered.host = pgEnv.POSTGRES_HOST || 'localhost';
    discovered.port = pgEnv.POSTGRES_PORT || '5432';
    discovered.user = pgEnv.POSTGRES_USER || 'postgres';
    discovered.password = pgEnv.POSTGRES_PASSWORD || 'postgres';
    discovered.database = pgEnv.VPN_DATABASE || 'vpn_saas';
    discovered.source = 'postgres-env';
    return discovered;
  }

  // 4. Docker compose postgres service
  const dockerPs = await runCmd('docker ps --format "{{.Names}}||{{.Ports}}" 2>nul', { timeout: 5000 });
  if (dockerPs.success && dockerPs.stdout) {
    for (const line of dockerPs.stdout.split('\n')) {
      const [name, ports] = line.split('||');
      if (name && (name.includes('postgres') || name.includes('pg'))) {
        // Extract host port mapping like 0.0.0.0:5432->5432/tcp
        const portMatch = ports && ports.match(/(\d+):\d+->\d+/);
        if (portMatch) {
          discovered.host = 'localhost';
          discovered.port = portMatch[1];
          discovered.user = existingEnv.POSTGRES_USER || 'postgres';
          discovered.password = existingEnv.POSTGRES_PASSWORD || 'postgres';
          discovered.database = existingEnv.VPN_DATABASE || 'vpn_saas';
          discovered.source = 'docker-container';
          return discovered;
        }
      }
    }
  }

  // 5. Probe localhost:5432
  const net = require('net');
  const probePort = parseInt(existingEnv.POSTGRES_PORT || '5432', 10);
  const tcpOk = await new Promise((resolve) => {
    const sock = net.createConnection({ host: 'localhost', port: probePort }, () => { sock.end(); resolve(true); });
    sock.on('error', () => resolve(false));
    sock.setTimeout(3000, () => { sock.destroy(); resolve(false); });
  });
  if (tcpOk) {
    discovered.host = 'localhost';
    discovered.port = String(probePort);
    discovered.user = existingEnv.POSTGRES_USER || 'postgres';
    discovered.password = existingEnv.POSTGRES_PASSWORD || 'postgres';
    discovered.database = existingEnv.VPN_DATABASE || 'vpn_saas';
    discovered.source = 'local-probe';
    return discovered;
  }

  return discovered;
}

/**
 * Discover 3X-UI panel configuration from installer-state, .env, and Docker.
 */
async function discoverXUI(existingEnv, state) {
  const discovered = { baseUrl: null, username: null, password: null, subPort: null, subPath: null, source: null };

  // 1. installer-state validated entry
  const confirmedEntry = getValidatedEntry(state, 'xui.confirmed', { minConfidence: 'low' });
  if (confirmedEntry && confirmedEntry.value && confirmedEntry.value.baseUrl) {
    discovered.baseUrl = confirmedEntry.value.baseUrl;
    discovered.source = 'installer-state';
  }

  // 2. .env values
  if (!discovered.baseUrl) {
    discovered.baseUrl = existingEnv.XUI_PANEL_URL || existingEnv.SANITY_PANEL_BASE_URL || null;
    if (discovered.baseUrl) discovered.source = 'env';
  }
  discovered.username = existingEnv.XUI_USERNAME || existingEnv.SANITY_PANEL_USERNAME || null;
  discovered.password = existingEnv.XUI_PASSWORD || existingEnv.SANITY_PANEL_PASSWORD || null;
  discovered.subPort = existingEnv.SANITY_PANEL_SUB_PORT || '2053';
  discovered.subPath = existingEnv.SANITY_PANEL_SUB_PATH || 'sub';

  // 3. Docker container detection
  if (!discovered.baseUrl) {
    const dockerPs = await runCmd('docker ps --format "{{.Names}}||{{.Ports}}" 2>nul', { timeout: 5000 });
    if (dockerPs.success && dockerPs.stdout) {
      for (const line of dockerPs.stdout.split('\n')) {
        const [name, ports] = line.split('||');
        if (name && (name.includes('xui') || name.includes('3x'))) {
          const portMatch = ports && ports.match(/(\d+):\d+->(\d+)/);
          if (portMatch) {
            discovered.baseUrl = `http://localhost:${portMatch[1]}`;
            discovered.source = 'docker-container';
            break;
          }
        }
      }
    }
  }

  return discovered;
}

/**
 * Discover Telegram bot configuration.
 */
function discoverTelegram(existingEnv) {
  return {
    botToken: existingEnv.TELEGRAM_BOT_TOKEN || null,
    adminIds: existingEnv.TELEGRAM_ADMIN_IDS || null,
  };
}

// ── Main auto-config runner ─────────────────────────────────────────

/**
 * Run the full auto-configuration flow.
 * @param {object} opts - { nonInteractive: bool, env: object (override) }
 * @returns {Promise<{config: object, changed: string[], prompts: object}>}
 */
async function runAutoConfig(opts = {}) {
  const nonInteractive = !!opts.nonInteractive;
  const state = loadState(STATE_PATH);
  const existingEnv = opts.env || loadEnvFile(ENV_PATH);
  const exampleEnv = loadEnvFile(ENV_EXAMPLE_PATH);
  const changed = [];
  const prompts = {};

  // Start with existing .env values, fall back to .env.example defaults
  const config = {};
  for (const [k, v] of Object.entries(exampleEnv)) {
    config[k] = existingEnv[k] !== undefined ? existingEnv[k] : v;
  }
  // Also include any keys in existing .env not in example
  for (const [k, v] of Object.entries(existingEnv)) {
    if (config[k] === undefined) config[k] = v;
  }

  // ── PostgreSQL ──
  console.log('\n[1/5] Discovering PostgreSQL...');
  const pg = await discoverPostgreSQL(config);
  if (pg.host) {
    console.log(`  ✓ Found PostgreSQL via ${pg.source}: ${pg.host}:${pg.port}/${pg.database}`);
    config.POSTGRES_HOST = pg.host;
    config.POSTGRES_PORT = pg.port;
    config.POSTGRES_USER = pg.user;
    config.POSTGRES_PASSWORD = pg.password;
    config.VPN_DATABASE = pg.database;
    if (pg.databaseUrl) {
      config.DATABASE_URL = pg.databaseUrl;
    } else {
      config.DATABASE_URL = `postgresql://${pg.user}:${pg.password}@${pg.host}:${pg.port}/${pg.database}?schema=public`;
    }
    changed.push('postgresql');
    setEntry(state, 'db.discovered', pg, { source: pg.source, confidence: 'high', ttlSeconds: 3600 });
  } else {
    console.log('  ✗ PostgreSQL not found — will use defaults');
    if (!config.DATABASE_URL) {
      config.DATABASE_URL = `postgresql://${config.POSTGRES_USER}:${config.POSTGRES_PASSWORD}@${config.POSTGRES_HOST}:${config.POSTGRES_PORT}/${config.VPN_DATABASE}?schema=public`;
    }
  }

  // ── 3X-UI ──
  console.log('\n[2/5] Discovering 3X-UI panel...');
  const xui = await discoverXUI(config, state);
  if (xui.baseUrl) {
    console.log(`  ✓ Found 3X-UI via ${xui.source}: ${xui.baseUrl}`);
    config.XUI_PANEL_URL = xui.baseUrl;
    config.SANITY_PANEL_BASE_URL = xui.baseUrl;
    if (xui.username) {
      config.XUI_USERNAME = xui.username;
      config.SANITY_PANEL_USERNAME = xui.username;
    }
    if (xui.password) {
      config.XUI_PASSWORD = xui.password;
      config.SANITY_PANEL_PASSWORD = xui.password;
    }
    config.SANITY_PANEL_SUB_PORT = xui.subPort;
    config.SANITY_PANEL_SUB_PATH = xui.subPath;
    changed.push('xui');
    setEntry(state, 'xui.autoConfig', xui, { source: xui.source, confidence: 'high', ttlSeconds: 3600 });
  } else {
    console.log('  ✗ 3X-UI panel not found — will need manual configuration');
  }

  // ── Generate secrets (JWT, S3, encryption, webhook) ──
  console.log('\n[3/5] Generating missing secrets...');
  const secretsToGenerate = [
    { key: 'JWT_ACCESS_SECRET', length: 48 },
    { key: 'JWT_REFRESH_SECRET', length: 48 },
    { key: 'ENCRYPTION_KEY', length: 32 },
    { key: 'WEBHOOK_SECRET', length: 32 },
  ];
  for (const { key, length } of secretsToGenerate) {
    const current = config[key] || '';
    const isDefault = !current || current.includes('change-me') || current.length < 16;
    if (isDefault) {
      config[key] = generateSecret(length);
      console.log(`  ✓ Generated ${key}`);
      changed.push(key);
    } else {
      console.log(`  ✓ ${key} already set (keeping existing)`);
    }
  }

  // S3 keys — generate if still default
  if (!config.S3_ACCESS_KEY || config.S3_ACCESS_KEY === 'minioadmin') {
    config.S3_ACCESS_KEY = 'vpn-saas-' + generateSecret(12);
    console.log('  ✓ Generated S3_ACCESS_KEY');
    changed.push('S3_ACCESS_KEY');
  }
  if (!config.S3_SECRET_KEY || config.S3_SECRET_KEY === 'minioadmin') {
    config.S3_SECRET_KEY = generateSecret(32);
    console.log('  ✓ Generated S3_SECRET_KEY');
    changed.push('S3_SECRET_KEY');
  }

  // ── Telegram (only prompt if missing) ──
  console.log('\n[4/5] Checking Telegram configuration...');
  const tg = discoverTelegram(config);
  if (!tg.botToken || tg.botToken === '123456:ABC-DEF') {
    if (nonInteractive) {
      console.log('  ⊘ TELEGRAM_BOT_TOKEN not set (skipped in non-interactive mode)');
      prompts.TELEGRAM_BOT_TOKEN = null;
    } else {
      console.log('  ? TELEGRAM_BOT_TOKEN not found — prompting user');
      const token = await prompt('Enter your Telegram Bot Token (from @BotFather), or press Enter to skip:');
      if (token) {
        config.TELEGRAM_BOT_TOKEN = token;
        changed.push('TELEGRAM_BOT_TOKEN');
        console.log('  ✓ Telegram bot token saved');
      } else {
        console.log('  ⊘ Skipped — bot will not start until token is set');
      }
      prompts.TELEGRAM_BOT_TOKEN = token || null;
    }
  } else {
    console.log(`  ✓ TELEGRAM_BOT_TOKEN already set`);
  }

  if (!tg.adminIds || tg.adminIds === '123456789,987654321') {
    if (nonInteractive) {
      console.log('  ⊘ TELEGRAM_ADMIN_IDS not set (skipped in non-interactive mode)');
      prompts.TELEGRAM_ADMIN_IDS = null;
    } else {
      console.log('  ? TELEGRAM_ADMIN_IDS not found — prompting user');
      const adminIds = await prompt('Enter your Telegram Admin ID(s) (comma-separated, from @userinfobot), or press Enter to skip:');
      if (adminIds) {
        config.TELEGRAM_ADMIN_IDS = adminIds;
        changed.push('TELEGRAM_ADMIN_IDS');
        console.log('  ✓ Telegram admin IDs saved');
      }
      prompts.TELEGRAM_ADMIN_IDS = adminIds || null;
    }
  } else {
    console.log('  ✓ TELEGRAM_ADMIN_IDS already set');
  }

  // ── Write .env ──
  console.log('\n[5/5] Writing configuration to .env...');
  writeEnvFile(ENV_PATH, config);
  console.log(`  ✓ Configuration written to ${ENV_PATH}`);
  console.log(`  ✓ ${changed.length} value(s) updated`);

  // Save state
  setEntry(state, 'config.written', { envPath: ENV_PATH, changedKeys: changed }, { source: 'auto-config', confidence: 'high', ttlSeconds: 1800 });
  saveState(STATE_PATH, state);

  return { config, changed, prompts };
}

module.exports = { runAutoConfig, discoverPostgreSQL, discoverXUI, discoverTelegram, writeEnvFile, loadEnvFile, generateSecret, generatePassword };

// Run directly if invoked as a script
if (require.main === module) {
  runAutoConfig({ nonInteractive: process.argv.includes('--non-interactive') })
    .then(({ changed }) => {
      console.log('\n=== Auto-configuration complete ===');
      console.log(`Updated: ${changed.join(', ') || 'nothing'}`);
      process.exit(0);
    })
    .catch((e) => {
      console.error('Auto-config failed:', e.message || e);
      process.exit(1);
    });
}